<?php return array (
  'site_title' => 'Ex-Rate',
  'base_color' => '#10ce8c',
  'time_zone' => 'UTC',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'base_currency_rate' => 1.17,
  'theme' => 'exchanger',
  'fraction_number' => 2,
  'paginate' => 20,
  'email_verification' => 0,
  'email_notification' => 0,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'push_notification' => 0,
  'error_log' => 1,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 0,
  'is_active_cron_notification' => 1,
  'bonus_amount' => '20',
  'joining_bonus' => 1,
  'referral_bonus' => 1,
  'sender_email' => 'support@mail.com',
  'sender_email_name' => 'Bug Finder',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'smtp.mailtrap.io',
    'smtp_port' => '2525',
    'smtp_encryption' => 'tls',
    'smtp_username' => 'b75b1a5bfa5d58',
    'smtp_password' => 'f89fbe0495a7fc',
  ),
  'fiat_currency_api' => 'WXLRMqWaBZeZZ5c1qSV52eHVeyQVY7VW',
  'fiat_currency_status' => 0,
  'crypto_currency_api' => '1df68913f43debee2bca1bb8fd3b570de123f86dfe86cee17398270d1c6eac35',
  'crypto_currency_status' => 0,
);