<?php
$arr = [
    "Home",
    "About",
    "Services",
    "Blogs",
    "FAQ",
    "Contact",
    "Plan",
    "Login",
    "Logout",
    "Sign up",
    "Copyright",
    "All Rights Reserved",
    "Username",
    "Email Or Username",
    "Password",
    "Remember Me",
    "Forgot password?",
    "Don't have any account? Sign Up",
    "SIGN UP FORM",
    "Sponsor By",
    "First Name",
    "Last Name",
    "Email Address",
    "Your Phone Number",
    "Confirm Password",
    "Already have an account? Login",
    "Please confirm your password before continuing.",
    "Forgot Your Password?",
    "Already have an account?",
    "Reset Password",
    "Enter your Email Address",
    "Don't have an account?",
    "Send Password Reset Link",
    "New Password",
    "403 Forbidden",
    "You don’t have permission to access ‘/’ on this server.",
    "Back To Home",
    "Sorry page was not found!",
    "We're sorry, the page you requested could not be found. Please go back to the homepage or contact us at",
    "Method Not Allowed",
    "opps!",
    "Session has expired",
    "Dashboard",
    "Invest History",
    "Add Fund",
    "Fund History",
    "Transaction",
    "Payout",
    "Payout History",
    "My Referral",
    "Referral Bonus",
    "Profile Settings",
    "Support Ticket",
    "Main Balance",
    "Interest Balance",
    "Total Deposit",
    "Total Earn",
    "Account Statistics",
    "Total Invest",
    "Total Payout",
    "Total Ticket",
    "Total Referral Bonus",
    "Latest Registered Partner",
    "The last Referral Bonus",
    "Email",
    "Phone Number",
    "Joined At",
    "Code",
    "Pay Now",
    "Payment By",
    "Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Google Authenticator",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "Close",
    "Verify",
    "Verify Your OTP to Disable",
    "Transactions",
    "Search for Transaction ID",
    "Remark",
    "Search",
    "SL No.",
    "Transaction ID",
    "Amount",
    "Remarks",
    "Time",
    "Type Here",
    "All Payment",
    "Complete Payment",
    "Pending Payment",
    "Cancel Payment",
    "Gateway",
    "Charge",
    "Search Service",
    "Subject",
    "Image Upload",
    "Upload",
    "Last Reply",
    "Reply",
    "Open",
    "Answered",
    "Replied",
    "Customer Reply",
    "Closed",
    "Upload File",
    "Confirm",
    "Are you want to close ticket?",
    "My Profile",
    "Open Ticket",
    "Show Ticket",
    "No Data found",
    "Email Verification",
    "Update User",
    "Update Password",
    "Admin Feedback",
    "PAYOUT NOW",
    "Transaction Limit:",
    "Payout By",
    "Remove",
    "Confirm Now",
    "Return Interest",
    "Received Amount",
    "Upcoming Payment",
    "Search User",
    "Bonus From",
    "Current Password",
    "Address",
    "Submit",
    "Useful Links",
    "Deposit Balance",
    "2FA Security",
    "Referral Link",
    "Level",
    "Create account",
    "2 FA Code",
    "Email Verification Code",
    "Didn't get Code? Click to",
    "Resend Code",
    "Sms Verification",
    "Sms Verification Code",
    "Login here",
    "sign in",
    "Create An Account",
    "Sign up here",
    "Select Code",
    "sign Up",
    "Sign In",
    "Email Verify",
    "Verify Your Email Address",
    "A fresh verification link has been sent to your email address.",
    "Before proceeding, please check your email for a verification link.",
    "If you did not receive the email",
    "click here to request another",
    "Forbidden",
    "You don't have permission to access ‘/’ on this server",
    "404",
    "The page you are looking for was not found.",
    "405",
    "419",
    "Sorry, your session has expired",
    "500",
    "Internal Server Error",
    "The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator.",
    "Exchange rate",
    "Bank Reserve",
    "Register",
    "Sign out",
    "Exchange",
    "Clear all",
    "send",
    "Receive",
    "swap currencies",
    "Blog",
    "Support",
    "subscribe newsletter",
    "Enter email",
    "Previous",
    "Next",
    "Learn and earn",
    "Admin",
    "step 1",
    "Subscribe",
    "Information",
    "Exchange Id",
    "Amount Send",
    "Amount Receive",
    "Rate",
    "Additional information",
    "Process Exchange",
    "Transaction Confirmation",
    "Note",
    "Confirm Transaction",
    "Exchanges",
    "SL",
    "Exchange ID",
    "Send Amount",
    "Receive Amount",
    "Status",
    "More",
    "Pending",
    "Completed",
    "Rejected",
    "Send Currency",
    "Receive Currency",
    "Close",
    "Password Setting",
    "Preferred language",
    "Select Language",
    "Enter Subject",
    "Message",
    "Enter Message",
    "Create Ticket",
    "Action",
    "Ticket#",
    "No Data Found!",
    "File",
    "Confirmation",
    "Confirm",
    "Complete",
    "Cancel",
    "2 Step Security",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, install the Google Authenticator application on your mobile device.",
    "Enter Google Authenticator Code",
    "About Us",
    "Read more",
    "Full name",
    "Email address",
    "Send",
    "Email us",
    "Call Now",
    "Processed",
    "Timeout",
    "Currency",
    "Sell Rate",
    "Buy Rate",
    "Customer",
    "Testimonial",
    "Add New",
    "still no have testimonial",
    "Comment",
    "Your message",
    "Balance",
    "Complete Exchange",
    "Pending Exchange",
    "Cancel Exchange",
    "Automatically top up your account balance by sharing your referral link, Earn a percentage of whatever plan your referred user buys.",
    "Direct Referral Member",
    "Pay Out",
    "Request Amount",
    "Charge Amount",
    "Total Payable",
    "Available Balance",
    "Additional Information To Withdraw Confirm",


];
return $arr;
